# Generated by Django 5.1.5 on 2025-02-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_choice_choice_text_remove_choice_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.TextField(default='enter a question?'),
        ),
    ]
